config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "restaurants#home"
  # get "/restaurants", to: "restaurants#index"
  # get "/restaurants/new", to: "restaurants#new"
  # post "/restaurants", to: "restaurants#create"
  # get "/restaurants/:id", to: "restaurants#show", as: :restaurant
  # get "/restaurants/:id/edit", to: "restaurants#edit", as: :edit_restaurant
  # patch "/restaurants/:id", to: "restaurants#update"
  # delete "/restaurants/:id", to: "restaurants#destroy"
  resources :restaurants do
    resources :reviews, only: %i[new create]
    collection do
      get :top
      get :random
      # get "/restaurants/top", to: :restaurants#top", as: :top_restaurants
    end
    member do
      get :chef
    end
  end
  resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  # allows us to do: @restaurant.reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  # allows us to do: @review.restaurant
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurants, only: %i[show edit update destroy chef]
  def home
  end
  
  def index
    @restaurants = Restaurant.all
  end

  def show
    set_restaurants
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    restaurant = Restaurant.new(restaurant_params)
    restaurant.save
    redirect_to restaurant_path(restaurant)
  end

  def edit
    set_restaurants
  end

  def update
    set_restaurants
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    set_restaurants
    @restaurant.destroy
    redirect_to restaurants_path, status: :see_other
  end

  def top
    @restaurants = Restaurant.where(rating: 5)
  end

  def chef
    set_restaurants
    @chef_name = @restaurant.chef_name
  end

  def random

    @restaurant = Restaurant.all.sample


  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating)
  end

  def set_restaurants
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]
  def new
    set_restaurant
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCrud</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

app/views/restaurants/chef.html.erb
<div class="container pt-5">
  <h1><%= @restaurant.name %>'s Chef is:</h1>
  <h3><%= @chef_name %></h3>

  <%= link_to "Back to Restaurant", restaurant_path(@restaurant) %>
</div>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/home.html.erb
<div class="jumbotron jumbotron-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8cmVzdGF1cmFudHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
    <h1 class="display-4">Check Out Our Restaurants</h1>


  </div>
</div>



<div class="home-card-container">
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1569702824812-351205c9cde5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Zm9ya3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60)">
  <%= link_to "All Restaurants", restaurants_path, class: "home-links" %>
</div>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1569702824812-351205c9cde5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Zm9ya3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60)">
  <%= link_to "Top Rated Restaurants", top_restaurants_path, class: "home-links" %>
</div>

<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://images.unsplash.com/photo-1569702824812-351205c9cde5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Zm9ya3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=800&q=60)">
  Can't choose?
  <p><%= link_to "We'll choose for you", random_restaurants_path, class: "home-links" %></p>
</div>

</div>


</div>

<div class="jumbotron2 jumbotron-fluid">
  <div class="container">
    <h1 class="display-4"></h1>
    <p class="lead"></p>

  </div>
</div>

app/views/restaurants/index.html.erb
<div class="jumbotron jumbotron-fluid" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1586208958839-06c17cacdf08?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzB8fGtpdGNoZW58ZW58MHx8MHx8&auto=format&fit=crop&w=800&q=60)">
  <div class="container">
    <h1 class="display-4">Here are all of our restaurants</h1>


  </div>
</div>

<div class="card-container">
    <% @restaurants.each do|restaurant| %>
      <div class="card" style="width: 18rem;">
         <h5 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= restaurant.address %></h6>
         <h6 class="p text-muted">Rating:  <%= "⭐️" * restaurant.rating %></h6>
         </div>
               <% end %>

      <%= link_to "Back to home", root_path %>
  </div>

app/views/restaurants/new.html.erb
<h1>Create a new restaurant</h1>

<%= render "form", restaurant: @restaurant %>

app/views/restaurants/random.html.erb
  <div class="container">
  <h1>Try this one!</h1>
  <h2><%=@restaurant.name %></h2>

  <p>Rating:  <%= "⭐️" * @restaurant.rating %></p>
  <p>Located in: <%= @restaurant.address %></p>
  <%= link_to "Back to home page", restaurants_path  %>

  </div>

app/views/restaurants/show.html.erb
<div class="banner">
  <h1 class="show-name"><%=@restaurant.name %></h1>

  <p class="show-p">Rating:  <%= "⭐️" * @restaurant.rating %></p>
  <p class="show-p">Located in: <%= @restaurant.address %></p>

  <%= link_to "Link to see Chef", chef_restaurant_path(@restaurant) %>

  <p class="show-p"><strong>Reviews</strong></p>
  <p><%= link_to "Add Review", new_restaurant_review_path(@restaurant) %></p>
  <ul class="list-group">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
        <%= review.content %>
        <%= link_to "Delete",
          review_path(review),
          data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
        </li>

    <% end %>
  </ul>
  <hr>

  <%= link_to "Back to restaurants", restaurants_path %>
  <%= link_to "Edit", edit_restaurant_path %>
  <%= link_to "Delete",
    restaurant_path(@restaurant),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
</div>

app/views/restaurants/top.html.erb
<div class="container">
  <h1>Top Rated Restaurants:</h1>

<div class="card-container">
    <% @restaurants.each do|restaurant| %>
      <div class="card" style="width: 18rem;">
         <h5 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant) %></h5>
         <h6 class="card-subtitle mb-2 text-muted"><%= restaurant.address %></h6>
         </div>
               <% end %>
  </div>

app/views/reviews/new.html.erb
<div class="container pt-5">
  <h1>New Review</h1>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.submit "Submit Review", class: "btn btn-primary" %>
  <% end %>
</div>